export { useAuth } from './useAuth';
export type { User } from './useAuth';
export { usePatients } from './usePatients';
export { useAppointments } from './useAppointments';
export { useErrorToast } from './useErrorToast';
export { useMediaQuery, useBreakpoint, useResponsive } from './useMediaQuery';
export { useOnboarding } from './useOnboarding';
export { useLanguage } from './useLanguage';
export type { UseLanguageReturn } from './useLanguage';
export { useFocusTrap } from './useFocusTrap';
export type { UseFocusTrapOptions } from './useFocusTrap';
